# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\pyconlyse\views\ui\ProjectManager.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProjectManager(object):
    def setupUi(self, ProjectManager):
        ProjectManager.setObjectName("ProjectManager")
        ProjectManager.resize(787, 644)
        self.centralwidget = QtWidgets.QWidget(ProjectManager)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_group = QtWidgets.QHBoxLayout()
        self.horizontalLayout_group.setObjectName("horizontalLayout_group")
        self.groupBox_files = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_files.setObjectName("groupBox_files")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_files)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView_file = QtWidgets.QTreeView(self.groupBox_files)
        self.treeView_file.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_file.sizePolicy().hasHeightForWidth())
        self.treeView_file.setSizePolicy(sizePolicy)
        self.treeView_file.setMinimumSize(QtCore.QSize(300, 350))
        self.treeView_file.setBaseSize(QtCore.QSize(0, 0))
        self.treeView_file.setObjectName("treeView_file")
        self.horizontalLayout.addWidget(self.treeView_file)
        self.verticalLayout_files_action = QtWidgets.QVBoxLayout()
        self.verticalLayout_files_action.setContentsMargins(10, 20, 10, -1)
        self.verticalLayout_files_action.setObjectName("verticalLayout_files_action")
        self.groupBox_actions = QtWidgets.QGroupBox(self.groupBox_files)
        self.groupBox_actions.setObjectName("groupBox_actions")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_actions)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_open = QtWidgets.QPushButton(self.groupBox_actions)
        self.pushButton_open.setObjectName("pushButton_open")
        self.verticalLayout.addWidget(self.pushButton_open)
        self.pushButton_create_project = QtWidgets.QPushButton(self.groupBox_actions)
        self.pushButton_create_project.setObjectName("pushButton_create_project")
        self.verticalLayout.addWidget(self.pushButton_create_project)
        self.pushButton_rename = QtWidgets.QPushButton(self.groupBox_actions)
        self.pushButton_rename.setObjectName("pushButton_rename")
        self.verticalLayout.addWidget(self.pushButton_rename)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_actions)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_delete = QtWidgets.QPushButton(self.groupBox_actions)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.verticalLayout.addWidget(self.pushButton_delete)
        self.verticalLayout_files_action.addWidget(self.groupBox_actions)
        self.groupBox_retreive = QtWidgets.QGroupBox(self.groupBox_files)
        self.groupBox_retreive.setObjectName("groupBox_retreive")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_retreive)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_get_projects = QtWidgets.QPushButton(self.groupBox_retreive)
        self.pushButton_get_projects.setObjectName("pushButton_get_projects")
        self.verticalLayout_3.addWidget(self.pushButton_get_projects)
        self.label_projects_number = QtWidgets.QLabel(self.groupBox_retreive)
        self.label_projects_number.setObjectName("label_projects_number")
        self.verticalLayout_3.addWidget(self.label_projects_number)
        self.pushButton_get_files = QtWidgets.QPushButton(self.groupBox_retreive)
        self.pushButton_get_files.setObjectName("pushButton_get_files")
        self.verticalLayout_3.addWidget(self.pushButton_get_files)
        self.label_files_number = QtWidgets.QLabel(self.groupBox_retreive)
        self.label_files_number.setObjectName("label_files_number")
        self.verticalLayout_3.addWidget(self.label_files_number)
        self.pushButton_get_users = QtWidgets.QPushButton(self.groupBox_retreive)
        self.pushButton_get_users.setObjectName("pushButton_get_users")
        self.verticalLayout_3.addWidget(self.pushButton_get_users)
        self.label_users_number = QtWidgets.QLabel(self.groupBox_retreive)
        self.label_users_number.setObjectName("label_users_number")
        self.verticalLayout_3.addWidget(self.label_users_number)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_files_action.addWidget(self.groupBox_retreive)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_files_action.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_files_action)
        self.groupBox_description = QtWidgets.QGroupBox(self.groupBox_files)
        self.groupBox_description.setObjectName("groupBox_description")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_description)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeView_description = QtWidgets.QTreeView(self.groupBox_description)
        self.treeView_description.setMinimumSize(QtCore.QSize(300, 350))
        self.treeView_description.setObjectName("treeView_description")
        self.verticalLayout_2.addWidget(self.treeView_description)
        self.label_search = QtWidgets.QLabel(self.groupBox_description)
        self.label_search.setObjectName("label_search")
        self.verticalLayout_2.addWidget(self.label_search)
        self.lineEdit_search = QtWidgets.QLineEdit(self.groupBox_description)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.verticalLayout_2.addWidget(self.lineEdit_search)
        self.horizontalLayout.addWidget(self.groupBox_description)
        self.horizontalLayout_group.addWidget(self.groupBox_files)
        self.verticalLayout_4.addLayout(self.horizontalLayout_group)
        self.comments = QtWidgets.QTextEdit(self.centralwidget)
        self.comments.setMaximumSize(QtCore.QSize(16777215, 50))
        self.comments.setObjectName("comments")
        self.verticalLayout_4.addWidget(self.comments)
        ProjectManager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProjectManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 21))
        self.menubar.setObjectName("menubar")
        ProjectManager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProjectManager)
        self.statusbar.setObjectName("statusbar")
        ProjectManager.setStatusBar(self.statusbar)

        self.retranslateUi(ProjectManager)
        QtCore.QMetaObject.connectSlotsByName(ProjectManager)

    def retranslateUi(self, ProjectManager):
        _translate = QtCore.QCoreApplication.translate
        ProjectManager.setWindowTitle(_translate("ProjectManager", "Project Manager"))
        self.groupBox_files.setTitle(_translate("ProjectManager", "File tree"))
        self.groupBox_actions.setTitle(_translate("ProjectManager", "Actions"))
        self.pushButton_open.setText(_translate("ProjectManager", "Open"))
        self.pushButton_create_project.setText(_translate("ProjectManager", "Create New"))
        self.pushButton_rename.setText(_translate("ProjectManager", "Rename"))
        self.pushButton.setText(_translate("ProjectManager", "Update"))
        self.pushButton_delete.setText(_translate("ProjectManager", "Delete"))
        self.groupBox_retreive.setTitle(_translate("ProjectManager", "Retrieve"))
        self.pushButton_get_projects.setText(_translate("ProjectManager", "Get Projects"))
        self.label_projects_number.setText(_translate("ProjectManager", "Projects: "))
        self.pushButton_get_files.setText(_translate("ProjectManager", "Get Files"))
        self.label_files_number.setText(_translate("ProjectManager", "Files: "))
        self.pushButton_get_users.setText(_translate("ProjectManager", "Get Users"))
        self.label_users_number.setText(_translate("ProjectManager", "Users: "))
        self.groupBox_description.setTitle(_translate("ProjectManager", "Description"))
        self.label_search.setText(_translate("ProjectManager", "Search"))

