# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuperUser.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SuperUser(object):
    def setupUi(self, SuperClient):
        SuperClient.setObjectName("SuperClient")
        SuperClient.resize(828, 630)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        SuperClient.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/client_cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SuperClient.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SuperClient)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DevicesLayout = QtWidgets.QHBoxLayout()
        self.DevicesLayout.setContentsMargins(-1, -1, 0, 0)
        self.DevicesLayout.setObjectName("DevicesLayout")
        self.lW_devices = QtWidgets.QListWidget(self.centralwidget)
        self.lW_devices.setObjectName("lW_devices")
        self.DevicesLayout.addWidget(self.lW_devices)
        self.InfoLayout = QtWidgets.QVBoxLayout()
        self.InfoLayout.setContentsMargins(-1, -1, -1, 0)
        self.InfoLayout.setObjectName("InfoLayout")
        self.pB_connection = QtWidgets.QPushButton(self.centralwidget)
        self.pB_connection.setObjectName("pB_connection")
        self.InfoLayout.addWidget(self.pB_connection)
        self.chooseLayout = QtWidgets.QHBoxLayout()
        self.chooseLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.chooseLayout.setContentsMargins(-1, -1, -1, 0)
        self.chooseLayout.setObjectName("chooseLayout")
        self.rB_window = QtWidgets.QRadioButton(self.centralwidget)
        self.rB_window.setObjectName("rB_window")
        self.chooseLayout.addWidget(self.rB_window)
        self.rB_local = QtWidgets.QRadioButton(self.centralwidget)
        self.rB_local.setObjectName("rB_local")
        self.chooseLayout.addWidget(self.rB_local)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.chooseLayout.addItem(spacerItem)
        self.InfoLayout.addLayout(self.chooseLayout)
        self.tE_info = QtWidgets.QTextEdit(self.centralwidget)
        self.tE_info.setObjectName("tE_info")
        self.InfoLayout.addWidget(self.tE_info)
        self.DevicesLayout.addLayout(self.InfoLayout)
        self.verticalLayout_2.addLayout(self.DevicesLayout)
        self.executionLayout = QtWidgets.QHBoxLayout()
        self.executionLayout.setContentsMargins(-1, 2, -1, 2)
        self.executionLayout.setObjectName("executionLayout")
        self.lE_command = QtWidgets.QLineEdit(self.centralwidget)
        self.lE_command.setObjectName("lE_command")
        self.executionLayout.addWidget(self.lE_command)
        self.pB_execute = QtWidgets.QPushButton(self.centralwidget)
        self.pB_execute.setObjectName("pB_execute")
        self.executionLayout.addWidget(self.pB_execute)
        self.verticalLayout_2.addLayout(self.executionLayout)
        SuperClient.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SuperClient)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 21))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        SuperClient.setMenuBar(self.menubar)
        self.actionSettings = QtWidgets.QAction(SuperClient)
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuit = QtWidgets.QAction(SuperClient)
        self.actionQuit.setObjectName("actionQuit")
        self.menuMain.addAction(self.actionSettings)
        self.menuMain.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(SuperClient)
        QtCore.QMetaObject.connectSlotsByName(SuperClient)

    def retranslateUi(self, SuperClient):
        _translate = QtCore.QCoreApplication.translate
        SuperClient.setWindowTitle(_translate("SuperClient", "SuperClient"))
        self.pB_connection.setText(_translate("SuperClient", "Create Connection"))
        self.rB_window.setText(_translate("SuperClient", "Window"))
        self.rB_local.setText(_translate("SuperClient", "Terminal"))
        self.pB_execute.setText(_translate("SuperClient", "Execute"))
        self.menuMain.setTitle(_translate("SuperClient", "Main"))
        self.actionSettings.setText(_translate("SuperClient", "Settings"))
        self.actionQuit.setText(_translate("SuperClient", "Quit"))

