# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Server_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServerGUI(object):
    def setupUi(self, ServerMainWindow):
        ServerMainWindow.setObjectName("ServerMainWindow")
        ServerMainWindow.resize(819, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ServerMainWindow.sizePolicy().hasHeightForWidth())
        ServerMainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/serverGUI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ServerMainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ServerMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vl_queue = QtWidgets.QVBoxLayout()
        self.vl_queue.setObjectName("vl_queue")
        self.label_queue = QtWidgets.QLabel(self.centralwidget)
        self.label_queue.setObjectName("label_queue")
        self.vl_queue.addWidget(self.label_queue)
        self.tE_queue_in = QtWidgets.QTextEdit(self.centralwidget)
        self.tE_queue_in.setMaximumSize(QtCore.QSize(16777215, 600))
        self.tE_queue_in.setObjectName("tE_queue_in")
        self.vl_queue.addWidget(self.tE_queue_in)
        self.horizontalLayout.addLayout(self.vl_queue)
        self.vl_pending = QtWidgets.QVBoxLayout()
        self.vl_pending.setObjectName("vl_pending")
        self.label_pending = QtWidgets.QLabel(self.centralwidget)
        self.label_pending.setObjectName("label_pending")
        self.vl_pending.addWidget(self.label_pending)
        self.tE_queue_in_pending = QtWidgets.QTextEdit(self.centralwidget)
        self.tE_queue_in_pending.setMaximumSize(QtCore.QSize(16777215, 600))
        self.tE_queue_in_pending.setObjectName("tE_queue_in_pending")
        self.vl_pending.addWidget(self.tE_queue_in_pending)
        self.horizontalLayout.addLayout(self.vl_pending)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.tE_queue_out = QtWidgets.QTextEdit(self.centralwidget)
        self.tE_queue_out.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tE_queue_out.setObjectName("tE_queue_out")
        self.verticalLayout_9.addWidget(self.tE_queue_out)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tE_output = QtWidgets.QTextEdit(self.centralwidget)
        self.tE_output.setObjectName("tE_output")
        self.verticalLayout.addWidget(self.tE_output)
        self.lE_execute = QtWidgets.QLineEdit(self.centralwidget)
        self.lE_execute.setObjectName("lE_execute")
        self.verticalLayout.addWidget(self.lE_execute)
        self.pB_execute = QtWidgets.QPushButton(self.centralwidget)
        self.pB_execute.setObjectName("pB_execute")
        self.verticalLayout.addWidget(self.pB_execute)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_10.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pB_start = QtWidgets.QPushButton(self.centralwidget)
        self.pB_start.setAutoFillBackground(True)
        self.pB_start.setObjectName("pB_start")
        self.verticalLayout_3.addWidget(self.pB_start)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.rB_hb = QtWidgets.QRadioButton(self.centralwidget)
        self.rB_hb.setText("")
        self.rB_hb.setObjectName("rB_hb")
        self.horizontalLayout_4.addWidget(self.rB_hb)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.pB_pause = QtWidgets.QPushButton(self.centralwidget)
        self.pB_pause.setEnabled(False)
        self.pB_pause.setObjectName("pB_pause")
        self.verticalLayout_3.addWidget(self.pB_pause)
        self.pB_status = QtWidgets.QPushButton(self.centralwidget)
        self.pB_status.setObjectName("pB_status")
        self.verticalLayout_3.addWidget(self.pB_status)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.lE_serverinfo = QtWidgets.QLineEdit(self.centralwidget)
        self.lE_serverinfo.setObjectName("lE_serverinfo")
        self.verticalLayout_7.addWidget(self.lE_serverinfo)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.tE_services_running = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tE_services_running.sizePolicy().hasHeightForWidth())
        self.tE_services_running.setSizePolicy(sizePolicy)
        self.tE_services_running.setMinimumSize(QtCore.QSize(350, 150))
        self.tE_services_running.setMaximumSize(QtCore.QSize(500, 500))
        self.tE_services_running.setObjectName("tE_services_running")
        self.verticalLayout_5.addWidget(self.tE_services_running)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.tE_events_running = QtWidgets.QTextEdit(self.centralwidget)
        self.tE_events_running.setMinimumSize(QtCore.QSize(350, 150))
        self.tE_events_running.setMaximumSize(QtCore.QSize(500, 500))
        self.tE_events_running.setObjectName("tE_events_running")
        self.verticalLayout_6.addWidget(self.tE_events_running)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        ServerMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ServerMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 21))
        self.menubar.setObjectName("menubar")
        self.menusdf = QtWidgets.QMenu(self.menubar)
        self.menusdf.setObjectName("menusdf")
        ServerMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ServerMainWindow)
        self.statusbar.setObjectName("statusbar")
        ServerMainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(ServerMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menubar.addAction(self.menusdf.menuAction())

        self.retranslateUi(ServerMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ServerMainWindow)

    def retranslateUi(self, ServerMainWindow):
        _translate = QtCore.QCoreApplication.translate
        ServerMainWindow.setWindowTitle(_translate("ServerMainWindow", "ServerGUI"))
        self.label_queue.setText(_translate("ServerMainWindow", "REQUEST Queue"))
        self.label_pending.setText(_translate("ServerMainWindow", "REQUESTS Pending"))
        self.label_6.setText(_translate("ServerMainWindow", "REPLY Queue"))
        self.label_2.setText(_translate("ServerMainWindow", "Executation output"))
        self.pB_execute.setText(_translate("ServerMainWindow", "execute"))
        self.pB_start.setText(_translate("ServerMainWindow", "Click to start"))
        self.pB_pause.setText(_translate("ServerMainWindow", "Click to pause"))
        self.pB_status.setText(_translate("ServerMainWindow", "Check status"))
        self.label.setText(_translate("ServerMainWindow", "ServerINFO:"))
        self.label_3.setText(_translate("ServerMainWindow", "Services running"))
        self.label_4.setText(_translate("ServerMainWindow", "Events running"))
        self.menusdf.setTitle(_translate("ServerMainWindow", "Settings"))
        self.actionExit.setText(_translate("ServerMainWindow", "actionExit"))


