# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_widget_u.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormSettings(object):
    def setupUi(self, FormSettings):
        FormSettings.setObjectName("FormSettings")
        FormSettings.resize(446, 628)
        FormSettings.setAcceptDrops(True)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(FormSettings)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layoutmain = QtWidgets.QVBoxLayout()
        self.layoutmain.setObjectName("layoutmain")
        self.Hardware = QtWidgets.QTabWidget(FormSettings)
        self.Hardware.setObjectName("Hardware")
        self.tab_DL = QtWidgets.QWidget()
        self.tab_DL.setObjectName("tab_DL")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_DL)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxAcc_G = QtWidgets.QGroupBox(self.tab_DL)
        self.groupBoxAcc_G.setObjectName("groupBoxAcc_G")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBoxAcc_G)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_Acc_X_G = QtWidgets.QLabel(self.groupBoxAcc_G)
        self.label_Acc_X_G.setObjectName("label_Acc_X_G")
        self.gridLayout_8.addWidget(self.label_Acc_X_G, 0, 0, 1, 1)
        self.lineEdit_Acc_X_G = QtWidgets.QLineEdit(self.groupBoxAcc_G)
        self.lineEdit_Acc_X_G.setObjectName("lineEdit_Acc_X_G")
        self.gridLayout_8.addWidget(self.lineEdit_Acc_X_G, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 2, 1, 1)
        self.label_Acc_Y_G = QtWidgets.QLabel(self.groupBoxAcc_G)
        self.label_Acc_Y_G.setObjectName("label_Acc_Y_G")
        self.gridLayout_8.addWidget(self.label_Acc_Y_G, 1, 0, 1, 1)
        self.lineEdit_Acc_Y_G = QtWidgets.QLineEdit(self.groupBoxAcc_G)
        self.lineEdit_Acc_Y_G.setObjectName("lineEdit_Acc_Y_G")
        self.gridLayout_8.addWidget(self.lineEdit_Acc_Y_G, 1, 1, 1, 1)
        self.label_Acc_Z_G = QtWidgets.QLabel(self.groupBoxAcc_G)
        self.label_Acc_Z_G.setObjectName("label_Acc_Z_G")
        self.gridLayout_8.addWidget(self.label_Acc_Z_G, 2, 0, 1, 1)
        self.lineEdit_Acc_Z_G = QtWidgets.QLineEdit(self.groupBoxAcc_G)
        self.lineEdit_Acc_Z_G.setObjectName("lineEdit_Acc_Z_G")
        self.gridLayout_8.addWidget(self.lineEdit_Acc_Z_G, 2, 1, 1, 1)
        self.label_Acc_A_G = QtWidgets.QLabel(self.groupBoxAcc_G)
        self.label_Acc_A_G.setObjectName("label_Acc_A_G")
        self.gridLayout_8.addWidget(self.label_Acc_A_G, 3, 0, 1, 1)
        self.lineEdit_Acc_A_G = QtWidgets.QLineEdit(self.groupBoxAcc_G)
        self.lineEdit_Acc_A_G.setObjectName("lineEdit_Acc_A_G")
        self.gridLayout_8.addWidget(self.lineEdit_Acc_A_G, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBoxAcc_G, 0, 0, 1, 1)
        self.groupBox_MC_G = QtWidgets.QGroupBox(self.tab_DL)
        self.groupBox_MC_G.setObjectName("groupBox_MC_G")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_MC_G)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_MC_X_G = QtWidgets.QLabel(self.groupBox_MC_G)
        self.label_MC_X_G.setObjectName("label_MC_X_G")
        self.gridLayout_11.addWidget(self.label_MC_X_G, 0, 0, 1, 1)
        self.lineEdit_MC_X_G = QtWidgets.QLineEdit(self.groupBox_MC_G)
        self.lineEdit_MC_X_G.setObjectName("lineEdit_MC_X_G")
        self.gridLayout_11.addWidget(self.lineEdit_MC_X_G, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 0, 2, 1, 1)
        self.label_MC_Y_G = QtWidgets.QLabel(self.groupBox_MC_G)
        self.label_MC_Y_G.setObjectName("label_MC_Y_G")
        self.gridLayout_11.addWidget(self.label_MC_Y_G, 1, 0, 1, 1)
        self.lineEdit_MC_Y_G = QtWidgets.QLineEdit(self.groupBox_MC_G)
        self.lineEdit_MC_Y_G.setObjectName("lineEdit_MC_Y_G")
        self.gridLayout_11.addWidget(self.lineEdit_MC_Y_G, 1, 1, 1, 1)
        self.label_MC_Z_G = QtWidgets.QLabel(self.groupBox_MC_G)
        self.label_MC_Z_G.setObjectName("label_MC_Z_G")
        self.gridLayout_11.addWidget(self.label_MC_Z_G, 2, 0, 1, 1)
        self.lineEdit_MC_Z_G = QtWidgets.QLineEdit(self.groupBox_MC_G)
        self.lineEdit_MC_Z_G.setObjectName("lineEdit_MC_Z_G")
        self.gridLayout_11.addWidget(self.lineEdit_MC_Z_G, 2, 1, 1, 1)
        self.label_MC_A_G = QtWidgets.QLabel(self.groupBox_MC_G)
        self.label_MC_A_G.setObjectName("label_MC_A_G")
        self.gridLayout_11.addWidget(self.label_MC_A_G, 3, 0, 1, 1)
        self.lineEdit_MC_A_G = QtWidgets.QLineEdit(self.groupBox_MC_G)
        self.lineEdit_MC_A_G.setObjectName("lineEdit_MC_A_G")
        self.gridLayout_11.addWidget(self.lineEdit_MC_A_G, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem3, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_MC_G, 0, 2, 1, 1)
        self.groupBox_Dim_G = QtWidgets.QGroupBox(self.tab_DL)
        self.groupBox_Dim_G.setObjectName("groupBox_Dim_G")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_Dim_G)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_Dim_X_G = QtWidgets.QLabel(self.groupBox_Dim_G)
        self.label_Dim_X_G.setObjectName("label_Dim_X_G")
        self.gridLayout_7.addWidget(self.label_Dim_X_G, 0, 0, 1, 1)
        self.lineEdit_Dim_X_G = QtWidgets.QLineEdit(self.groupBox_Dim_G)
        self.lineEdit_Dim_X_G.setObjectName("lineEdit_Dim_X_G")
        self.gridLayout_7.addWidget(self.lineEdit_Dim_X_G, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 2, 1, 1)
        self.label_Dim_Y_G = QtWidgets.QLabel(self.groupBox_Dim_G)
        self.label_Dim_Y_G.setObjectName("label_Dim_Y_G")
        self.gridLayout_7.addWidget(self.label_Dim_Y_G, 1, 0, 1, 1)
        self.lineEdit_Dim_Y_G = QtWidgets.QLineEdit(self.groupBox_Dim_G)
        self.lineEdit_Dim_Y_G.setObjectName("lineEdit_Dim_Y_G")
        self.gridLayout_7.addWidget(self.lineEdit_Dim_Y_G, 1, 1, 1, 1)
        self.label_Dim_Z_G = QtWidgets.QLabel(self.groupBox_Dim_G)
        self.label_Dim_Z_G.setObjectName("label_Dim_Z_G")
        self.gridLayout_7.addWidget(self.label_Dim_Z_G, 2, 0, 1, 1)
        self.lineEdit_Dim_Z_G = QtWidgets.QLineEdit(self.groupBox_Dim_G)
        self.lineEdit_Dim_Z_G.setObjectName("lineEdit_Dim_Z_G")
        self.gridLayout_7.addWidget(self.lineEdit_Dim_Z_G, 2, 1, 1, 1)
        self.label_Dim_A_G = QtWidgets.QLabel(self.groupBox_Dim_G)
        self.label_Dim_A_G.setObjectName("label_Dim_A_G")
        self.gridLayout_7.addWidget(self.label_Dim_A_G, 3, 0, 1, 1)
        self.lineEdit_Dim_A_G = QtWidgets.QLineEdit(self.groupBox_Dim_G)
        self.lineEdit_Dim_A_G.setObjectName("lineEdit_Dim_A_G")
        self.gridLayout_7.addWidget(self.lineEdit_Dim_A_G, 3, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_Dim_G, 1, 0, 1, 1)
        self.groupBoxVelocities_G = QtWidgets.QGroupBox(self.tab_DL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxVelocities_G.sizePolicy().hasHeightForWidth())
        self.groupBoxVelocities_G.setSizePolicy(sizePolicy)
        self.groupBoxVelocities_G.setObjectName("groupBoxVelocities_G")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBoxVelocities_G)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_Vel_X_G = QtWidgets.QLabel(self.groupBoxVelocities_G)
        self.label_Vel_X_G.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Vel_X_G.setObjectName("label_Vel_X_G")
        self.gridLayout_10.addWidget(self.label_Vel_X_G, 0, 0, 1, 1)
        self.lineEdit_Vel_X_G = QtWidgets.QLineEdit(self.groupBoxVelocities_G)
        self.lineEdit_Vel_X_G.setObjectName("lineEdit_Vel_X_G")
        self.gridLayout_10.addWidget(self.lineEdit_Vel_X_G, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBoxVelocities_G)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_Vel_Y_G = QtWidgets.QLabel(self.groupBoxVelocities_G)
        self.label_Vel_Y_G.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Vel_Y_G.setObjectName("label_Vel_Y_G")
        self.gridLayout_10.addWidget(self.label_Vel_Y_G, 1, 0, 1, 1)
        self.lineEdit_Vel_Y_G = QtWidgets.QLineEdit(self.groupBoxVelocities_G)
        self.lineEdit_Vel_Y_G.setObjectName("lineEdit_Vel_Y_G")
        self.gridLayout_10.addWidget(self.lineEdit_Vel_Y_G, 1, 1, 1, 1)
        self.label_Vel_Z_G = QtWidgets.QLabel(self.groupBoxVelocities_G)
        self.label_Vel_Z_G.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Vel_Z_G.setObjectName("label_Vel_Z_G")
        self.gridLayout_10.addWidget(self.label_Vel_Z_G, 2, 0, 1, 1)
        self.lineEdit_Vel_Z_G = QtWidgets.QLineEdit(self.groupBoxVelocities_G)
        self.lineEdit_Vel_Z_G.setObjectName("lineEdit_Vel_Z_G")
        self.gridLayout_10.addWidget(self.lineEdit_Vel_Z_G, 2, 1, 1, 1)
        self.label_Vel_A_G = QtWidgets.QLabel(self.groupBoxVelocities_G)
        self.label_Vel_A_G.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Vel_A_G.setObjectName("label_Vel_A_G")
        self.gridLayout_10.addWidget(self.label_Vel_A_G, 3, 0, 1, 1)
        self.lineEdit_Vel_A_G = QtWidgets.QLineEdit(self.groupBoxVelocities_G)
        self.lineEdit_Vel_A_G.setObjectName("lineEdit_Vel_A_G")
        self.gridLayout_10.addWidget(self.lineEdit_Vel_A_G, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem7, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBoxVelocities_G, 0, 1, 1, 1)
        self.groupBox_Pitches_G = QtWidgets.QGroupBox(self.tab_DL)
        self.groupBox_Pitches_G.setObjectName("groupBox_Pitches_G")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_Pitches_G)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_Pitches_X_G = QtWidgets.QLineEdit(self.groupBox_Pitches_G)
        self.lineEdit_Pitches_X_G.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Pitches_X_G.sizePolicy().hasHeightForWidth())
        self.lineEdit_Pitches_X_G.setSizePolicy(sizePolicy)
        self.lineEdit_Pitches_X_G.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_Pitches_X_G.setMaxLength(5)
        self.lineEdit_Pitches_X_G.setObjectName("lineEdit_Pitches_X_G")
        self.gridLayout_6.addWidget(self.lineEdit_Pitches_X_G, 0, 1, 1, 1)
        self.label_Pitches_Z_G = QtWidgets.QLabel(self.groupBox_Pitches_G)
        self.label_Pitches_Z_G.setObjectName("label_Pitches_Z_G")
        self.gridLayout_6.addWidget(self.label_Pitches_Z_G, 2, 0, 1, 1)
        self.label_Pitches_Y_G = QtWidgets.QLabel(self.groupBox_Pitches_G)
        self.label_Pitches_Y_G.setObjectName("label_Pitches_Y_G")
        self.gridLayout_6.addWidget(self.label_Pitches_Y_G, 1, 0, 1, 1)
        self.lineEdit_Pitches_Z_G = QtWidgets.QLineEdit(self.groupBox_Pitches_G)
        self.lineEdit_Pitches_Z_G.setObjectName("lineEdit_Pitches_Z_G")
        self.gridLayout_6.addWidget(self.lineEdit_Pitches_Z_G, 2, 1, 1, 1)
        self.label_Pitches_A_G = QtWidgets.QLabel(self.groupBox_Pitches_G)
        self.label_Pitches_A_G.setObjectName("label_Pitches_A_G")
        self.gridLayout_6.addWidget(self.label_Pitches_A_G, 3, 0, 1, 1)
        self.lineEdit_Pitches_Y_G = QtWidgets.QLineEdit(self.groupBox_Pitches_G)
        self.lineEdit_Pitches_Y_G.setObjectName("lineEdit_Pitches_Y_G")
        self.gridLayout_6.addWidget(self.lineEdit_Pitches_Y_G, 1, 1, 1, 1)
        self.lineEdit_Pitches_A_G = QtWidgets.QLineEdit(self.groupBox_Pitches_G)
        self.lineEdit_Pitches_A_G.setObjectName("lineEdit_Pitches_A_G")
        self.gridLayout_6.addWidget(self.lineEdit_Pitches_A_G, 3, 1, 1, 1)
        self.label_Pitches_X_G = QtWidgets.QLabel(self.groupBox_Pitches_G)
        self.label_Pitches_X_G.setMaximumSize(QtCore.QSize(7, 16777215))
        self.label_Pitches_X_G.setObjectName("label_Pitches_X_G")
        self.gridLayout_6.addWidget(self.label_Pitches_X_G, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem8, 4, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_Pitches_G, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.layoutDL = QtWidgets.QVBoxLayout()
        self.layoutDL.setObjectName("layoutDL")
        self.tabWidget_DL = QtWidgets.QTabWidget(self.tab_DL)
        self.tabWidget_DL.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget_DL.setObjectName("tabWidget_DL")
        self.tabLDL = QtWidgets.QWidget()
        self.tabLDL.setObjectName("tabLDL")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tabLDL)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_Ranges_L = QtWidgets.QGroupBox(self.tabLDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Ranges_L.sizePolicy().hasHeightForWidth())
        self.groupBox_Ranges_L.setSizePolicy(sizePolicy)
        self.groupBox_Ranges_L.setObjectName("groupBox_Ranges_L")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_Ranges_L)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_Ranges_zero_L = QtWidgets.QLineEdit(self.groupBox_Ranges_L)
        self.lineEdit_Ranges_zero_L.setInputMask("")
        self.lineEdit_Ranges_zero_L.setMaxLength(32767)
        self.lineEdit_Ranges_zero_L.setObjectName("lineEdit_Ranges_zero_L")
        self.gridLayout_4.addWidget(self.lineEdit_Ranges_zero_L, 2, 1, 1, 1)
        self.label_Ranges_max_L = QtWidgets.QLabel(self.groupBox_Ranges_L)
        self.label_Ranges_max_L.setObjectName("label_Ranges_max_L")
        self.gridLayout_4.addWidget(self.label_Ranges_max_L, 1, 0, 1, 1)
        self.lineEdit_Ranges_min_L = QtWidgets.QLineEdit(self.groupBox_Ranges_L)
        self.lineEdit_Ranges_min_L.setInputMask("")
        self.lineEdit_Ranges_min_L.setMaxLength(32767)
        self.lineEdit_Ranges_min_L.setObjectName("lineEdit_Ranges_min_L")
        self.gridLayout_4.addWidget(self.lineEdit_Ranges_min_L, 0, 1, 1, 1)
        self.label_Ranges_zero_L = QtWidgets.QLabel(self.groupBox_Ranges_L)
        self.label_Ranges_zero_L.setObjectName("label_Ranges_zero_L")
        self.gridLayout_4.addWidget(self.label_Ranges_zero_L, 2, 0, 1, 1)
        self.lineEdit_Ranges_max_L = QtWidgets.QLineEdit(self.groupBox_Ranges_L)
        self.lineEdit_Ranges_max_L.setInputMask("")
        self.lineEdit_Ranges_max_L.setText("")
        self.lineEdit_Ranges_max_L.setMaxLength(32767)
        self.lineEdit_Ranges_max_L.setObjectName("lineEdit_Ranges_max_L")
        self.gridLayout_4.addWidget(self.lineEdit_Ranges_max_L, 1, 1, 1, 1)
        self.label_Ranges_min_L = QtWidgets.QLabel(self.groupBox_Ranges_L)
        self.label_Ranges_min_L.setObjectName("label_Ranges_min_L")
        self.gridLayout_4.addWidget(self.label_Ranges_min_L, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_Ranges_L, 0, 5, 1, 1)
        self.lineEdit_Vel_Saxisvel_L = QtWidgets.QLineEdit(self.tabLDL)
        self.lineEdit_Vel_Saxisvel_L.setObjectName("lineEdit_Vel_Saxisvel_L")
        self.gridLayout_9.addWidget(self.lineEdit_Vel_Saxisvel_L, 0, 3, 1, 1)
        self.label_Vel_Saxis_L = QtWidgets.QLabel(self.tabLDL)
        self.label_Vel_Saxis_L.setObjectName("label_Vel_Saxis_L")
        self.gridLayout_9.addWidget(self.label_Vel_Saxis_L, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 0, 6, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 0, 4, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stepmotors.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_DL.addTab(self.tabLDL, icon, "")
        self.tabSDL = QtWidgets.QWidget()
        self.tabSDL.setObjectName("tabSDL")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabSDL)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Vel_Saxis_S = QtWidgets.QLabel(self.tabSDL)
        self.label_Vel_Saxis_S.setObjectName("label_Vel_Saxis_S")
        self.horizontalLayout_2.addWidget(self.label_Vel_Saxis_S)
        self.lineEdit_Vel_Saxisvel_S = QtWidgets.QLineEdit(self.tabSDL)
        self.lineEdit_Vel_Saxisvel_S.setObjectName("lineEdit_Vel_Saxisvel_S")
        self.horizontalLayout_2.addWidget(self.lineEdit_Vel_Saxisvel_S)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.groupBox_Ranges_S = QtWidgets.QGroupBox(self.tabSDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Ranges_S.sizePolicy().hasHeightForWidth())
        self.groupBox_Ranges_S.setSizePolicy(sizePolicy)
        self.groupBox_Ranges_S.setObjectName("groupBox_Ranges_S")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_Ranges_S)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Ranges_min_S = QtWidgets.QLabel(self.groupBox_Ranges_S)
        self.label_Ranges_min_S.setObjectName("label_Ranges_min_S")
        self.gridLayout_2.addWidget(self.label_Ranges_min_S, 0, 0, 1, 1)
        self.lineEdit_Ranges_min_S = QtWidgets.QLineEdit(self.groupBox_Ranges_S)
        self.lineEdit_Ranges_min_S.setInputMask("")
        self.lineEdit_Ranges_min_S.setMaxLength(32767)
        self.lineEdit_Ranges_min_S.setObjectName("lineEdit_Ranges_min_S")
        self.gridLayout_2.addWidget(self.lineEdit_Ranges_min_S, 0, 1, 1, 1)
        self.label_Ranges_max_S = QtWidgets.QLabel(self.groupBox_Ranges_S)
        self.label_Ranges_max_S.setObjectName("label_Ranges_max_S")
        self.gridLayout_2.addWidget(self.label_Ranges_max_S, 1, 0, 1, 1)
        self.lineEdit_Ranges_max_S = QtWidgets.QLineEdit(self.groupBox_Ranges_S)
        self.lineEdit_Ranges_max_S.setInputMask("")
        self.lineEdit_Ranges_max_S.setText("")
        self.lineEdit_Ranges_max_S.setMaxLength(32767)
        self.lineEdit_Ranges_max_S.setObjectName("lineEdit_Ranges_max_S")
        self.gridLayout_2.addWidget(self.lineEdit_Ranges_max_S, 1, 1, 1, 1)
        self.lineEdit_Ranges_zero_S = QtWidgets.QLineEdit(self.groupBox_Ranges_S)
        self.lineEdit_Ranges_zero_S.setInputMask("")
        self.lineEdit_Ranges_zero_S.setMaxLength(32767)
        self.lineEdit_Ranges_zero_S.setObjectName("lineEdit_Ranges_zero_S")
        self.gridLayout_2.addWidget(self.lineEdit_Ranges_zero_S, 2, 1, 1, 1)
        self.label_Ranges_zero_S = QtWidgets.QLabel(self.groupBox_Ranges_S)
        self.label_Ranges_zero_S.setObjectName("label_Ranges_zero_S")
        self.gridLayout_2.addWidget(self.label_Ranges_zero_S, 2, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_Ranges_S, 0, 0, 1, 1)
        self.groupBox_cells_pos = QtWidgets.QGroupBox(self.tabSDL)
        self.groupBox_cells_pos.setObjectName("groupBox_cells_pos")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_cells_pos)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_C4_S = QtWidgets.QLabel(self.groupBox_cells_pos)
        self.label_C4_S.setObjectName("label_C4_S")
        self.gridLayout_5.addWidget(self.label_C4_S, 4, 0, 1, 1)
        self.lineEdit_cells_C4_S = QtWidgets.QLineEdit(self.groupBox_cells_pos)
        self.lineEdit_cells_C4_S.setObjectName("lineEdit_cells_C4_S")
        self.gridLayout_5.addWidget(self.lineEdit_cells_C4_S, 4, 1, 1, 1)
        self.lineEdit_cells_CL_S = QtWidgets.QLineEdit(self.groupBox_cells_pos)
        self.lineEdit_cells_CL_S.setObjectName("lineEdit_cells_CL_S")
        self.gridLayout_5.addWidget(self.lineEdit_cells_CL_S, 5, 1, 1, 1)
        self.label_C4_Lanex = QtWidgets.QLabel(self.groupBox_cells_pos)
        self.label_C4_Lanex.setObjectName("label_C4_Lanex")
        self.gridLayout_5.addWidget(self.label_C4_Lanex, 5, 0, 1, 1)
        self.lineEdit_cells_C3_S = QtWidgets.QLineEdit(self.groupBox_cells_pos)
        self.lineEdit_cells_C3_S.setObjectName("lineEdit_cells_C3_S")
        self.gridLayout_5.addWidget(self.lineEdit_cells_C3_S, 3, 1, 1, 1)
        self.lineEdit_cells_CS_S = QtWidgets.QLineEdit(self.groupBox_cells_pos)
        self.lineEdit_cells_CS_S.setObjectName("lineEdit_cells_CS_S")
        self.gridLayout_5.addWidget(self.lineEdit_cells_CS_S, 2, 1, 1, 1)
        self.label_C3_S = QtWidgets.QLabel(self.groupBox_cells_pos)
        self.label_C3_S.setObjectName("label_C3_S")
        self.gridLayout_5.addWidget(self.label_C3_S, 3, 0, 1, 1)
        self.label_C1_S = QtWidgets.QLabel(self.groupBox_cells_pos)
        self.label_C1_S.setObjectName("label_C1_S")
        self.gridLayout_5.addWidget(self.label_C1_S, 0, 0, 1, 1)
        self.lineEdit_cells_C1_S = QtWidgets.QLineEdit(self.groupBox_cells_pos)
        self.lineEdit_cells_C1_S.setObjectName("lineEdit_cells_C1_S")
        self.gridLayout_5.addWidget(self.lineEdit_cells_C1_S, 0, 1, 1, 1)
        self.label_C2_S = QtWidgets.QLabel(self.groupBox_cells_pos)
        self.label_C2_S.setObjectName("label_C2_S")
        self.gridLayout_5.addWidget(self.label_C2_S, 1, 0, 1, 1)
        self.lineEdit_cells_C2_S = QtWidgets.QLineEdit(self.groupBox_cells_pos)
        self.lineEdit_cells_C2_S.setObjectName("lineEdit_cells_C2_S")
        self.gridLayout_5.addWidget(self.lineEdit_cells_C2_S, 1, 1, 1, 1)
        self.label_CS_S = QtWidgets.QLabel(self.groupBox_cells_pos)
        self.label_CS_S.setObjectName("label_CS_S")
        self.gridLayout_5.addWidget(self.label_CS_S, 2, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_cells_pos, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem13, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_13)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.tabWidget_DL.addTab(self.tabSDL, icon, "")
        self.layoutDL.addWidget(self.tabWidget_DL)
        self.verticalLayout.addLayout(self.layoutDL)
        self.Hardware.addTab(self.tab_DL, icon, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("spectrometer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Hardware.addTab(self.tab_4, icon1, "")
        self.layoutmain.addWidget(self.Hardware)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Buttonsavesettings = QtWidgets.QPushButton(FormSettings)
        self.Buttonsavesettings.setObjectName("Buttonsavesettings")
        self.horizontalLayout.addWidget(self.Buttonsavesettings)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.layoutmain.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.layoutmain)
        self.label_Acc_X_G.setBuddy(self.lineEdit_Acc_X_G)
        self.label_Acc_Y_G.setBuddy(self.lineEdit_Acc_Y_G)
        self.label_Acc_Z_G.setBuddy(self.lineEdit_Acc_Z_G)
        self.label_Acc_A_G.setBuddy(self.lineEdit_Acc_A_G)
        self.label_MC_X_G.setBuddy(self.lineEdit_MC_X_G)
        self.label_MC_Y_G.setBuddy(self.lineEdit_MC_Y_G)
        self.label_MC_Z_G.setBuddy(self.lineEdit_MC_Z_G)
        self.label_MC_A_G.setBuddy(self.lineEdit_MC_A_G)
        self.label_Dim_X_G.setBuddy(self.lineEdit_Dim_X_G)
        self.label_Dim_Y_G.setBuddy(self.lineEdit_Dim_Y_G)
        self.label_Dim_Z_G.setBuddy(self.lineEdit_Dim_Z_G)
        self.label_Dim_A_G.setBuddy(self.lineEdit_Dim_A_G)
        self.label_Vel_X_G.setBuddy(self.lineEdit_Vel_X_G)
        self.label_Vel_Y_G.setBuddy(self.lineEdit_Vel_Y_G)
        self.label_Vel_Z_G.setBuddy(self.lineEdit_Vel_Z_G)
        self.label_Vel_A_G.setBuddy(self.lineEdit_Vel_A_G)
        self.label_Pitches_Z_G.setBuddy(self.lineEdit_Pitches_Z_G)
        self.label_Pitches_Y_G.setBuddy(self.lineEdit_Pitches_Y_G)
        self.label_Pitches_A_G.setBuddy(self.lineEdit_Pitches_A_G)
        self.label_Pitches_X_G.setBuddy(self.lineEdit_Pitches_X_G)
        self.label_Ranges_max_L.setBuddy(self.lineEdit_Ranges_max_L)
        self.label_Ranges_zero_L.setBuddy(self.lineEdit_Ranges_zero_L)
        self.label_Ranges_min_L.setBuddy(self.lineEdit_Ranges_min_L)
        self.label_Vel_Saxis_L.setBuddy(self.lineEdit_Vel_Saxisvel_L)
        self.label_Vel_Saxis_S.setBuddy(self.lineEdit_Vel_Saxisvel_S)
        self.label_Ranges_min_S.setBuddy(self.lineEdit_Ranges_min_S)
        self.label_Ranges_max_S.setBuddy(self.lineEdit_Ranges_max_S)
        self.label_Ranges_zero_S.setBuddy(self.lineEdit_Ranges_zero_S)
        self.label_C4_S.setBuddy(self.lineEdit_cells_C4_S)
        self.label_C4_Lanex.setBuddy(self.lineEdit_cells_CL_S)
        self.label_C3_S.setBuddy(self.lineEdit_cells_C3_S)
        self.label_C1_S.setBuddy(self.lineEdit_cells_C1_S)
        self.label_C2_S.setBuddy(self.lineEdit_cells_C2_S)
        self.label_CS_S.setBuddy(self.lineEdit_cells_CS_S)

        self.retranslateUi(FormSettings)
        self.Hardware.setCurrentIndex(0)
        self.tabWidget_DL.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormSettings)
        FormSettings.setTabOrder(self.Hardware, self.lineEdit_Acc_X_G)
        FormSettings.setTabOrder(self.lineEdit_Acc_X_G, self.lineEdit_Acc_Y_G)
        FormSettings.setTabOrder(self.lineEdit_Acc_Y_G, self.lineEdit_Acc_Z_G)
        FormSettings.setTabOrder(self.lineEdit_Acc_Z_G, self.lineEdit_Acc_A_G)
        FormSettings.setTabOrder(self.lineEdit_Acc_A_G, self.lineEdit_Vel_X_G)
        FormSettings.setTabOrder(self.lineEdit_Vel_X_G, self.lineEdit_Vel_Y_G)
        FormSettings.setTabOrder(self.lineEdit_Vel_Y_G, self.lineEdit_Vel_Z_G)
        FormSettings.setTabOrder(self.lineEdit_Vel_Z_G, self.lineEdit_Vel_A_G)
        FormSettings.setTabOrder(self.lineEdit_Vel_A_G, self.lineEdit_MC_X_G)
        FormSettings.setTabOrder(self.lineEdit_MC_X_G, self.lineEdit_MC_Y_G)
        FormSettings.setTabOrder(self.lineEdit_MC_Y_G, self.lineEdit_MC_Z_G)
        FormSettings.setTabOrder(self.lineEdit_MC_Z_G, self.lineEdit_MC_A_G)
        FormSettings.setTabOrder(self.lineEdit_MC_A_G, self.lineEdit_Dim_X_G)
        FormSettings.setTabOrder(self.lineEdit_Dim_X_G, self.lineEdit_Dim_Y_G)
        FormSettings.setTabOrder(self.lineEdit_Dim_Y_G, self.lineEdit_Dim_Z_G)
        FormSettings.setTabOrder(self.lineEdit_Dim_Z_G, self.lineEdit_Dim_A_G)
        FormSettings.setTabOrder(self.lineEdit_Dim_A_G, self.lineEdit_Pitches_X_G)
        FormSettings.setTabOrder(self.lineEdit_Pitches_X_G, self.lineEdit_Pitches_Y_G)
        FormSettings.setTabOrder(self.lineEdit_Pitches_Y_G, self.lineEdit_Pitches_Z_G)
        FormSettings.setTabOrder(self.lineEdit_Pitches_Z_G, self.lineEdit_Pitches_A_G)
        FormSettings.setTabOrder(self.lineEdit_Pitches_A_G, self.tabWidget_DL)
        FormSettings.setTabOrder(self.tabWidget_DL, self.lineEdit_Vel_Saxisvel_L)
        FormSettings.setTabOrder(self.lineEdit_Vel_Saxisvel_L, self.lineEdit_Ranges_min_L)
        FormSettings.setTabOrder(self.lineEdit_Ranges_min_L, self.lineEdit_Ranges_max_L)
        FormSettings.setTabOrder(self.lineEdit_Ranges_max_L, self.lineEdit_Ranges_zero_L)
        FormSettings.setTabOrder(self.lineEdit_Ranges_zero_L, self.lineEdit_Ranges_min_S)
        FormSettings.setTabOrder(self.lineEdit_Ranges_min_S, self.lineEdit_Ranges_max_S)
        FormSettings.setTabOrder(self.lineEdit_Ranges_max_S, self.lineEdit_Ranges_zero_S)
        FormSettings.setTabOrder(self.lineEdit_Ranges_zero_S, self.lineEdit_cells_C1_S)
        FormSettings.setTabOrder(self.lineEdit_cells_C1_S, self.lineEdit_cells_C2_S)
        FormSettings.setTabOrder(self.lineEdit_cells_C2_S, self.lineEdit_cells_CS_S)
        FormSettings.setTabOrder(self.lineEdit_cells_CS_S, self.lineEdit_cells_C3_S)
        FormSettings.setTabOrder(self.lineEdit_cells_C3_S, self.lineEdit_cells_C4_S)
        FormSettings.setTabOrder(self.lineEdit_cells_C4_S, self.lineEdit_cells_CL_S)
        FormSettings.setTabOrder(self.lineEdit_cells_CL_S, self.Buttonsavesettings)

    def retranslateUi(self, FormSettings):
        _translate = QtCore.QCoreApplication.translate
        FormSettings.setWindowTitle(_translate("FormSettings", "Settings"))
        self.groupBoxAcc_G.setTitle(_translate("FormSettings", "Accelerations"))
        self.label_Acc_X_G.setText(_translate("FormSettings", "X"))
        self.label_Acc_Y_G.setText(_translate("FormSettings", "Y"))
        self.label_Acc_Z_G.setText(_translate("FormSettings", "Z"))
        self.label_Acc_A_G.setText(_translate("FormSettings", "A"))
        self.groupBox_MC_G.setTitle(_translate("FormSettings", "Motor currents"))
        self.label_MC_X_G.setText(_translate("FormSettings", "X"))
        self.label_MC_Y_G.setText(_translate("FormSettings", "Y"))
        self.label_MC_Z_G.setText(_translate("FormSettings", "Z"))
        self.label_MC_A_G.setText(_translate("FormSettings", "A"))
        self.groupBox_Dim_G.setTitle(_translate("FormSettings", "Dimension"))
        self.label_Dim_X_G.setText(_translate("FormSettings", "X"))
        self.label_Dim_Y_G.setText(_translate("FormSettings", "Y"))
        self.label_Dim_Z_G.setText(_translate("FormSettings", "Z"))
        self.label_Dim_A_G.setText(_translate("FormSettings", "A"))
        self.groupBoxVelocities_G.setTitle(_translate("FormSettings", "Velocities"))
        self.label_Vel_X_G.setText(_translate("FormSettings", "X"))
        self.label_Vel_Y_G.setText(_translate("FormSettings", "Y"))
        self.label_Vel_Z_G.setText(_translate("FormSettings", "Z"))
        self.label_Vel_A_G.setText(_translate("FormSettings", "A"))
        self.groupBox_Pitches_G.setTitle(_translate("FormSettings", "Pitches"))
        self.label_Pitches_Z_G.setText(_translate("FormSettings", "Z"))
        self.label_Pitches_Y_G.setText(_translate("FormSettings", "Y"))
        self.label_Pitches_A_G.setText(_translate("FormSettings", "A"))
        self.label_Pitches_X_G.setText(_translate("FormSettings", "X"))
        self.groupBox_Ranges_L.setTitle(_translate("FormSettings", "Ranges"))
        self.label_Ranges_max_L.setText(_translate("FormSettings", "Max"))
        self.label_Ranges_zero_L.setText(_translate("FormSettings", "Zero"))
        self.label_Ranges_min_L.setText(_translate("FormSettings", "Min"))
        self.label_Vel_Saxis_L.setText(_translate("FormSettings", "S/Axis velocity"))
        self.tabWidget_DL.setTabText(self.tabWidget_DL.indexOf(self.tabLDL), _translate("FormSettings", "Delay line long"))
        self.label_Vel_Saxis_S.setText(_translate("FormSettings", "S/Axis velocity"))
        self.groupBox_Ranges_S.setTitle(_translate("FormSettings", "Ranges"))
        self.label_Ranges_min_S.setText(_translate("FormSettings", "Min"))
        self.label_Ranges_max_S.setText(_translate("FormSettings", "Max"))
        self.label_Ranges_zero_S.setText(_translate("FormSettings", "Zero"))
        self.groupBox_cells_pos.setTitle(_translate("FormSettings", "Cells\' positions in mm"))
        self.label_C4_S.setText(_translate("FormSettings", "Cell4"))
        self.label_C4_Lanex.setText(_translate("FormSettings", "CL"))
        self.label_C3_S.setText(_translate("FormSettings", "Cell3"))
        self.label_C1_S.setText(_translate("FormSettings", "Cell1"))
        self.label_C2_S.setText(_translate("FormSettings", "Cell2"))
        self.label_CS_S.setText(_translate("FormSettings", "CellS"))
        self.tabWidget_DL.setTabText(self.tabWidget_DL.indexOf(self.tabSDL), _translate("FormSettings", "Delay line short"))
        self.Hardware.setTabText(self.Hardware.indexOf(self.tab_DL), _translate("FormSettings", "Delay lines"))
        self.Hardware.setTabText(self.Hardware.indexOf(self.tab_4), _translate("FormSettings", "Spectrometers"))
        self.Buttonsavesettings.setText(_translate("FormSettings", "Save Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormSettings = QtWidgets.QWidget()
    ui = Ui_FormSettings()
    ui.setupUi(FormSettings)
    FormSettings.show()
    sys.exit(app.exec_())

