# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_camera.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CameraWidget(object):
    def setupUi(self, CameraWidget, service_parameters):
        CameraWidget.setObjectName("CameraWidget")
        CameraWidget.setEnabled(True)
        CameraWidget.resize(646, 838)
        self.centralwidget = QtWidgets.QWidget(CameraWidget)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_blacklevel = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_blacklevel.setMinimum(-127)
        self.spinBox_blacklevel.setMaximum(127)
        self.spinBox_blacklevel.setObjectName("spinBox_blacklevel")
        self.gridLayout.addWidget(self.spinBox_blacklevel, 4, 3, 1, 1)
        self.spinBox_fps = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_fps.setMinimum(1)
        self.spinBox_fps.setMaximum(50)
        self.spinBox_fps.setProperty("value", 5)
        self.spinBox_fps.setObjectName("spinBox_fps")
        self.gridLayout.addWidget(self.spinBox_fps, 4, 2, 1, 1)
        self.spinBox_Xoffset = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Xoffset.setMaximum(2000)
        self.spinBox_Xoffset.setObjectName("spinBox_Xoffset")
        self.gridLayout.addWidget(self.spinBox_Xoffset, 6, 0, 1, 1)
        self.label_Yoffset = QtWidgets.QLabel(self.centralwidget)
        self.label_Yoffset.setObjectName("label_Yoffset")
        self.gridLayout.addWidget(self.label_Yoffset, 4, 1, 1, 1)
        self.label_Xshift = QtWidgets.QLabel(self.centralwidget)
        self.label_Xshift.setObjectName("label_Xshift")
        self.gridLayout.addWidget(self.label_Xshift, 7, 0, 1, 1)
        self.label_Ysize = QtWidgets.QLabel(self.centralwidget)
        self.label_Ysize.setObjectName("label_Ysize")
        self.gridLayout.addWidget(self.label_Ysize, 2, 1, 1, 1)
        self.spinBox_Xsize = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Xsize.sizePolicy().hasHeightForWidth())
        self.spinBox_Xsize.setSizePolicy(sizePolicy)
        self.spinBox_Xsize.setMaximum(2000)
        self.spinBox_Xsize.setObjectName("spinBox_Xsize")
        self.gridLayout.addWidget(self.spinBox_Xsize, 3, 0, 1, 1)
        self.label_Xoffset = QtWidgets.QLabel(self.centralwidget)
        self.label_Xoffset.setObjectName("label_Xoffset")
        self.gridLayout.addWidget(self.label_Xoffset, 4, 0, 1, 1)
        self.spinBox_Xshift = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Xshift.setMinimum(-500)
        self.spinBox_Xshift.setMaximum(500)
        self.spinBox_Xshift.setObjectName("spinBox_Xshift")
        self.gridLayout.addWidget(self.spinBox_Xshift, 8, 0, 1, 1)
        self.label_cameraID = QtWidgets.QLabel(self.centralwidget)
        self.label_cameraID.setObjectName("label_cameraID")
        self.gridLayout.addWidget(self.label_cameraID, 1, 0, 1, 1)
        self.label_Xsize = QtWidgets.QLabel(self.centralwidget)
        self.label_Xsize.setObjectName("label_Xsize")
        self.gridLayout.addWidget(self.label_Xsize, 2, 0, 1, 1)
        self.spinBox_cameraID = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cameraID.setObjectName("spinBox_cameraID")
        self.gridLayout.addWidget(self.spinBox_cameraID, 1, 1, 1, 1)
        self.spinBox_gainraw = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_gainraw.setMaximum(3)
        self.spinBox_gainraw.setObjectName("spinBox_gainraw")
        self.gridLayout.addWidget(self.spinBox_gainraw, 2, 3, 1, 1)
        self.spinBox_Ysize = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Ysize.sizePolicy().hasHeightForWidth())
        self.spinBox_Ysize.setSizePolicy(sizePolicy)
        self.spinBox_Ysize.setMinimum(0)
        self.spinBox_Ysize.setMaximum(2000)
        self.spinBox_Ysize.setProperty("value", 0)
        self.spinBox_Ysize.setObjectName("spinBox_Ysize")
        self.gridLayout.addWidget(self.spinBox_Ysize, 3, 1, 1, 1)
        self.spinBox_Yoffset = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Yoffset.setMaximum(2000)
        self.spinBox_Yoffset.setObjectName("spinBox_Yoffset")
        self.gridLayout.addWidget(self.spinBox_Yoffset, 6, 1, 1, 1)
        self.label_Yshift = QtWidgets.QLabel(self.centralwidget)
        self.label_Yshift.setObjectName("label_Yshift")
        self.gridLayout.addWidget(self.label_Yshift, 7, 1, 1, 1)
        self.spinBox_Yshift = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Yshift.setMinimum(-500)
        self.spinBox_Yshift.setMaximum(500)
        self.spinBox_Yshift.setObjectName("spinBox_Yshift")
        self.gridLayout.addWidget(self.spinBox_Yshift, 8, 1, 1, 1)
        self.checkBox_power = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_power.setObjectName("checkBox_power")
        self.gridLayout.addWidget(self.checkBox_power, 8, 2, 1, 1)
        self.checkBox_activate = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_activate.setObjectName("checkBox_activate")
        self.gridLayout.addWidget(self.checkBox_activate, 7, 2, 1, 1)
        self.checkBox_sync_clock = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_sync_clock.setObjectName("checkBox_sync_clock")
        self.gridLayout.addWidget(self.checkBox_sync_clock, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 2, 1, 1)
        self.checkBox_On = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_On.setObjectName("checkBox_On")
        self.gridLayout.addWidget(self.checkBox_On, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 6, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit_comments = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_comments.sizePolicy().hasHeightForWidth())
        self.textEdit_comments.setSizePolicy(sizePolicy)
        self.textEdit_comments.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.textEdit_comments.setObjectName("textEdit_comments")
        self.verticalLayout_3.addWidget(self.textEdit_comments)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.image = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setMinimumSize(QtCore.QSize(500, 500))
        self.image.setMaximumSize(QtCore.QSize(1200, 1200))
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_GetImage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_GetImage.setObjectName("pushButton_GetImage")
        self.horizontalLayout_2.addWidget(self.pushButton_GetImage)
        self.pushButton_GetImages = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_GetImages.setObjectName("pushButton_GetImages")
        self.horizontalLayout_2.addWidget(self.pushButton_GetImages)
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_2.addWidget(self.pushButton_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_RT = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_RT.setObjectName("radioButton_RT")
        self.horizontalLayout_3.addWidget(self.radioButton_RT)
        self.radioButton_every_n_sec = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_every_n_sec.setObjectName("radioButton_every_n_sec")
        self.horizontalLayout_3.addWidget(self.radioButton_every_n_sec)
        self.spinBox_seconds = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_seconds.setMinimum(1)
        self.spinBox_seconds.setMaximum(1000)
        self.spinBox_seconds.setObjectName("spinBox_seconds")
        self.horizontalLayout_3.addWidget(self.spinBox_seconds)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        CameraWidget.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CameraWidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 646, 21))
        self.menubar.setObjectName("menubar")
        CameraWidget.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CameraWidget)
        self.statusbar.setObjectName("statusbar")
        CameraWidget.setStatusBar(self.statusbar)

        self.retranslateUi(CameraWidget)
        QtCore.QMetaObject.connectSlotsByName(CameraWidget)

    def retranslateUi(self, CameraWidget):
        _translate = QtCore.QCoreApplication.translate
        CameraWidget.setWindowTitle(_translate("CameraWidget", "MainWindow"))
        self.label_Yoffset.setText(_translate("CameraWidget", "Yoffset"))
        self.label_Xshift.setText(_translate("CameraWidget", "Xshift"))
        self.label_Ysize.setText(_translate("CameraWidget", "Ysize"))
        self.label_Xoffset.setText(_translate("CameraWidget", "Xoffset"))
        self.label_cameraID.setText(_translate("CameraWidget", "#ID"))
        self.label_Xsize.setText(_translate("CameraWidget", "Xsize"))
        self.label_Yshift.setText(_translate("CameraWidget", "Yshift"))
        self.checkBox_power.setText(_translate("CameraWidget", "Power"))
        self.checkBox_activate.setText(_translate("CameraWidget", "Activate"))
        self.checkBox_sync_clock.setText(_translate("CameraWidget", "Sync"))
        self.label.setText(_translate("CameraWidget", "FPS"))
        self.checkBox_On.setText(_translate("CameraWidget", "On"))
        self.label_2.setText(_translate("CameraWidget", "GainRaw"))
        self.label_3.setText(_translate("CameraWidget", "BlackLevel"))
        self.pushButton_GetImage.setText(_translate("CameraWidget", "GetImage"))
        self.pushButton_GetImages.setText(_translate("CameraWidget", "GetImages"))
        self.pushButton_stop.setText(_translate("CameraWidget", "Stop"))
        self.radioButton_RT.setText(_translate("CameraWidget", "Real Time"))
        self.radioButton_every_n_sec.setText(_translate("CameraWidget", "Every n sec"))
