name: pyconlyse311
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - git
  - numpy=1.26.4
  - pyqt=5.15.*
  - pyqtgraph=0.13.7
  - requests=2.32.5
  - beautifulsoup4=4.12.3
  - pyzmq
  - pip:
      - git+https://github.com/MSLNZ/msl-equipment.git@main
      - git+https://github.com/MSLNZ/msl-equipment.git@main#subdirectory=packages/resources
